### ISSUE TITLE
Add optional '--config' flag

### ISSUE THREAD

**Issue by Nexxkinn** [lucacasonato/now-deno#23]
In the upcoming deno 1.0.0 release, clients can bundle a module with their own tsconfig file with `--config` flag, addressed in the release note in [v1.0.0-rc2 here](https://github.com/denoland/deno/releases/tag/v1.0.0-rc2)

Looking at the source code, the runtime hasn't implement this option yet.
https://github.com/lucacasonato/now-deno/blob/12d71952ac7ee3df058a3c8c267a869306466ebf/src/index.ts#L92

In addition, since it needs config file location, maybe creating new environment value `tsconfig` under  `env` parameter in `now.json` would be a good idea in this case.

**Comment by khrome83** [comment]
@Nexxkinn - the pull request should resolve this.

Let me know if you think any changes are needed.

See #26

**Comment by lucacasonato** [comment]
Merged in #26
