### ISSUE TITLE
Unable to add params outside of --unstable

### ISSUE THREAD

**Issue by khrome83** [lucacasonato/now-deno#25]
`note: Remember to include the --allow-read flag when rendering from files`

I noticed this when trying to access a file. Vercel allows `includedFiles` allowing lambdas to reference files that are compiled as part of it. Technically I don't think it "goes to disk", but I am seeing this permissions issues. 

Is this supported today, and not documented? Or is this adding additional ENV variables like DENO_UNSTABLE to support?

**Comment by lucacasonato** [comment]
You should have all permissions. All lambdas are run with --allow-all.

**Comment by khrome83** [comment]
when running `vercel dev` I get the permissions error. Is this handled by your package, or elsewhere? I opened a MR adding the flags, but maybe that was the wrong thing?

I see they are added to `deno bundle` i guess the permissions need run against `deno run`.

**Comment by khrome83** [comment]
Actually I see what happened.

```
LambdaError: template not found: _partials/contacts.html
note: Remember to include the --allow-read flag when rendering from files
```

This is a false flag. Deno spits out the warning to try and assist, but the path is wrong on the Lambda itself.

**Comment by lucacasonato** [comment]
Ah :-D

**Comment by khrome83** [comment]
Gonna close, thank you for the patience with me @lucacasonato
