### ISSUE TITLE
Change tags of repo

### ISSUE THREAD

**Issue by filiptronicek** [lucacasonato/now-deno#29]
Because of the change of name from Zeit to Vercel (blog post [here](https://vercel.com/blog/zeit-is-now-vercel)), it would be relevant to change the repo tags (topics) to reflect that
![image of repo topics - zeit-now,deno,lambda,serverless,zeit ](https://user-images.githubusercontent.com/29888641/82831306-60988200-9eb8-11ea-9f29-2d5acaaef025.png)

**Comment by lucacasonato** [comment]
Done :-)
